name: phys
channels:
  - default
  - conda-forge
  - eoas_ubc
dependencies:
  - python=3.7.*
  - sphinx=3
  - pip
  - runjb
  - git
  - pandas
  - matplotlib
  - scipy
  - pip:
    - jupyter-book>=0.7.0b
